In [1]:
# Check the right kernel is being used 

import sys
sys.executable

'/home/vscode/.cache/pypoetry/virtualenvs/twitter-sentiment-trading-strategy-QyUpulx_-py3.11/bin/python'

In [6]:
# Packages 

import duckdb

In [13]:
# Establish a connection to the DuckDB file that dbt writes models into.
# The path is relative to this notebook's location (notebooks/ → ../data/processed/)
con = duckdb.connect("../data/processed/sentiment.duckdb")

In [ ]:
# Run a SQL query against the database.
# Here we're previewing the first 20 rows of twitter_sentiment table ingested by the pipeline.
df = con.execute("select * from twitter_sentiment limit 20").df()

df.head()

,date,symbol,twitterPosts,twitterComments,twitterLikes,twitterImpressions,twitterSentiment
0,2021-11-18,AAPL,811,2592,21674,7981808,NaN
1,2021-11-18,ABT,21,3,13,64089,NaN
2,2021-11-18,AMD,150,675,2949,1645270,NaN
3,2021-11-18,AMZN,557,1315,12969,5590695,NaN
4,2021-11-18,ATVI,82,36,131,1310715,NaN

In [23]:
# Run a SQL query against the database.
# Here we're previewing the first 20 rows of prices_daily table ingested by the pipeline.
df = con.execute("select * from prices_daily limit 20").df()

df.head()

,date,symbol,Close,High,Low,Open,Volume
0,2021-01-04,A,114.659744,116.061095,113.181075,114.949683,2030700.0
1,2021-01-04,AAL,15.130000,15.880000,15.030000,15.850000,69732500.0
2,2021-01-04,AAP,139.792557,141.773864,138.566471,140.290100,849100.0
3,2021-01-04,AAPL,125.856697,129.941372,123.279459,129.853846,143301900.0
4,2021-01-04,ABBV,86.047386,87.631026,84.782101,87.492255,9523400.0

In [4]:
# Run a SQL query against the database.
# Here we're previewing the first 20 rows of nasdaq_prices_daily table ingested by the pipeline.
df = con.execute("select * from nasdaq_prices_daily limit 20").df()

df.head()

,date,symbol,Adj Close,Close,High,Low,Open,Volume
0,2021-01-04,QQQ,299.785187,309.309998,315.290009,305.179993,315.109985,45305900.0
1,2021-01-05,QQQ,302.256592,311.859985,312.140015,308.290009,308.290009,29323400.0
2,2021-01-06,QQQ,298.069641,307.540009,311.880005,305.980011,307.000000,52809600.0
3,2021-01-07,QQQ,305.280548,314.980011,315.839996,310.250000,310.279999,30394800.0
4,2021-01-08,QQQ,309.205872,319.029999,319.390015,315.079987,317.339996,33955800.0

In [ ]:

# Run a SQL query against the database.
# Here we're previewing the first 20 rows of stg_twitter_sentiment created by dbt.
df = con.execute("select * from stg_twitter_sentiment limit 20").df()

# Display the result as a pandas DataFrame for easy inspection
df.head()

,date,symbol,twitterPosts,twitterComments,twitterLikes,twitterImpressions,twitterSentiment
0,2021-11-18,AAPL,811,2592,21674,7981808,NaN
1,2021-11-18,ABT,21,3,13,64089,NaN
2,2021-11-18,AMD,150,675,2949,1645270,NaN
3,2021-11-18,AMZN,557,1315,12969,5590695,NaN
4,2021-11-18,ATVI,82,36,131,1310715,NaN

In [26]:

# Run a SQL query against the database.
# Here we're previewing the first 20 rows of stg_daily_stock_prices created by dbt.
df = con.execute("select * from stg_daily_stock_prices limit 20").df()

# Display the result as a pandas DataFrame for easy inspection
df.head()

,date,symbol,Open,High,Low,Close,Volume
0,2021-01-04,A,114.949683,116.061095,113.181075,114.659744,2030700.0
1,2021-01-04,AAL,15.850000,15.880000,15.030000,15.130000,69732500.0
2,2021-01-04,AAP,140.290100,141.773864,138.566471,139.792557,849100.0
3,2021-01-04,AAPL,129.853846,129.941372,123.279459,125.856697,143301900.0
4,2021-01-04,ABBV,87.492255,87.631026,84.782101,86.047386,9523400.0

In [8]:

# Run a SQL query against the database.
# Here we're previewing the first 20 rows of stg_nasdaq_prices created by dbt.
df = con.execute("select * from stg_nasdaq_prices limit 20").df()

# Display the result as a pandas DataFrame for easy inspection
df.head()

,date,symbol,Open,High,Low,Close,Adj Close,Volume
0,2021-01-04,QQQ,315.109985,315.290009,305.179993,309.309998,299.785187,45305900.0
1,2021-01-05,QQQ,308.290009,312.140015,308.290009,311.859985,302.256592,29323400.0
2,2021-01-06,QQQ,307.000000,311.880005,305.980011,307.540009,298.069641,52809600.0
3,2021-01-07,QQQ,310.279999,315.839996,310.250000,314.980011,305.280548,30394800.0
4,2021-01-08,QQQ,317.339996,319.390015,315.079987,319.029999,309.205872,33955800.0

In [ ]:
# Run a SQL query against the database.
# Here we're previewing the first 20 rows of int_twitter_sentiment created by dbt.
df = con.execute("select * from int_twitter_sentiment limit 20").df()

# Display the result as a pandas DataFrame for easy inspection
df.head()

,date,symbol,twitterPosts,twitterComments,twitterLikes,twitterImpressions,twitterSentiment,engagement_ratio
0,2021-11-18,AAPL,811,2592,21674,7981808,NaN,0.119590
1,2021-11-18,AMD,150,675,2949,1645270,NaN,0.228891
2,2021-11-18,AMZN,557,1315,12969,5590695,NaN,0.101396
3,2021-11-18,ATVI,82,36,131,1310715,NaN,0.274809
4,2021-11-18,BA,61,55,342,425847,NaN,0.160819

In [5]:
# Run a SQL query against the database.
# Here we're previewing the first 20 rows of int_avg_monthly_sentiment created by dbt.
df = con.execute("select * from int_avg_monthly_sentiment limit 20").df()

# Display the result as a pandas DataFrame for easy inspection
df.head()

       month symbol  engagement_ratio  rank
0 2021-11-01    OXY          2.147741     1
1 2021-11-01    AES          0.864613     2
2 2021-11-01   MNST          0.699721     3
3 2021-11-01    SLB          0.647374     4
4 2021-11-01    FCX          0.626323     5

In [4]:
# Run a SQL query against the database.
# Here we're previewing the first 20 rows of int_top5_monthly_stocks created by dbt.
df = con.execute("select * from int_top5_monthly_stocks limit 20").df()

# Display the result as a pandas DataFrame for easy inspection
df.head()

  investment_month symbol  engagement_ratio  rank
0       2021-12-01    OXY          2.147741     1
1       2021-12-01    AES          0.864613     2
2       2021-12-01   MNST          0.699721     3
3       2021-12-01    SLB          0.647374     4
4       2021-12-01    FCX          0.626323     5

In [29]:
# Run a SQL query against the database.
# Here we're previewing the first 20 rows of int_stocks_to_invest_by_month created by dbt.
df = con.execute("select * from int_stocks_to_invest_by_month limit 20").df()

# Display the result as a pandas DataFrame for easy inspection
df.head()

  investment_month symbol
0       2021-12-01    AES
1       2021-12-01    FCX
2       2021-12-01   MNST
3       2021-12-01    OXY
4       2021-12-01    SLB

In [30]:
# Run a SQL query against the database.
# Here we're previewing the first 20 rows of int_equal_weighted_portfolio_returns created by dbt.
df = con.execute("select * from int_equal_weighted_portfolio_returns limit 20").df()

# Display the result as a pandas DataFrame for easy inspection
df.head()

        date  portfolio_return
0 2021-12-01         -0.016417
1 2021-12-02          0.024872
2 2021-12-03         -0.007711
3 2021-12-06          0.023926
4 2021-12-07          0.030547

In [11]:
# Run a SQL query against the database.
# Here we're previewing the first 20 rows of int_nasdaq_returns created by dbt.
df = con.execute("select * from int_nasdaq_returns limit 20").df()

# Display the result as a pandas DataFrame for easy inspection
df.head()

        date  nasdaq_return
0 2021-01-04            NaN
1 2021-01-05       0.008210
2 2021-01-06      -0.013949
3 2021-01-07       0.023904
4 2021-01-08       0.012776

In [14]:
# Run a SQL query against the database.
# Here we're previewing the first 20 rows of portfolio_vs_nasdaq created by dbt.
df = con.execute("select * from portfolio_vs_nasdaq limit 20").df()

# Display the result as a pandas DataFrame for easy inspection
df.head()

        date  portfolio_return  nasdaq_return
0 2021-12-01         -0.016417      -0.017159
1 2021-12-02          0.024872       0.007181
2 2021-12-03         -0.007711      -0.017542
3 2021-12-06          0.023926       0.007981
4 2021-12-07          0.030547       0.029669

In [15]:
# Run a SQL query against the database.
# Here we're previewing the first 20 rows of strategy_performance created by dbt.
df = con.execute("select * from strategy_performance limit 20").df()

# Display the result as a pandas DataFrame for easy inspection
df.head()

,date,portfolio_return,nasdaq_return,portfolio_cumulative_return,nasdaq_cumulative_return,excess_return,cumulative_excess_return
0,2021-12-01,-0.016417,-0.017159,-0.016283,-0.017013,0.000742,0.000743
1,2021-12-02,0.024872,0.007181,0.008491,-0.009928,0.017690,0.018604
2,2021-12-03,-0.007711,-0.017542,0.000744,-0.027144,0.009830,0.028666
3,2021-12-06,0.023926,0.007981,0.024976,-0.019349,0.015945,0.045199
4,2021-12-07,0.030547,0.029669,0.056769,0.010182,0.000877,0.046117

In [17]:
# Close connection at the end of this run, to be able to run the dbt project

con.close()